---
title: "Assignment 0"
author: "Hongyu He (2632195) & Bruno Hoevelaken (2645065)"
date: "Group CS 6"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Exercise 0.6
#### 1. Plots for (a), (b), (c)
```{r echo=FALSE, out.width = '100%', out.height = '40%'}
par(mfrow=c(1,3))

# 0.6 a
sample1_data=as.matrix(read.table("sample1.txt"))
dimnames(sample1_data) <- list(
  list("a","b","c", "d"), 
  list("I", "II", "III", "IV", "V")
)
hist(
  sample1_data, 
  probability = T, 
  breaks = 5,
  main = "Histogram of Sample 1"
)

# 0.6 b
x  = seq(0, 2, 0.001)
y1 = x^4 
y2 = 5*x + 2

plot(
  x, y1, col = "blue", type = "l",
  main = "Plot for y1(x) and y2(x)",
  xlab = "x",
  ylab = "y"
)
lines(x, y2, col="red",  type = "l", lty = 2)

legend(
  0, 15,
  legend=c("y1 = x^4", "y2 = 5*x + 2"),
  col=c("blue", "red"), 
  lty=1:2, 
  cex=0.8
)


# 0.6 c
load("Ass0.RData")

barplot(
  table(school), 
  col = c("blue","green","black","yellow"),
  main = "Bar plot of \"school\" data"
)
```

#### 2. Plot for (d)
```{r echo=FALSE, out.width = '70%', out.height = '40%'}
# 0.6 d
par(mfrow=c(1,1))
proportions <- c(0.37,0.17,0.28,0.07,0.06,0.05)
food_lables <- c("Pear", "Cheesecake", "Chocolate", "Almond", "Strawberry", "Other")
pie(
  proportions,
  labels = food_lables,
  main="Sales proportions of pie flavours"
)
```

### Exercise 0.7
```r
// (a)
a07 = function(x){
  (x - 2)^2
}
// (b)
b07 = function(){
  takenSample = sample(1:100, 50, TRUE)
  nrPerColour = numeric(2)
  nrPerColour = c(sum(takenSample <= 30) / 50,
                  sum(takenSample >  30) / 50)
  nrPerColour
}
// (c)
c07 = function(n = 10, mr = 30, mw = 70){
  totalNrBalls   = mr+mw
  takenSample    = sample(1:totalNrBalls, n, TRUE)
  fractionVector = numeric(2)
  fractionVector = c(sum(takenSample <= mr) / n, 
                     sum(takenSample >  mr) / n)
  fractionVector
}
// (d)
d07 = function(){
  u = numeric(200)
  for(i in 1:200) {
    u[i] = median(sample(1:90, 40, TRUE))
  }
  u
}
```

## *Appendix*
Exercise 0.6 (a), (b), (c), (b)
```r
// (a)
par(mfrow=c(1,3))
sample1_data=as.matrix(read.table("sample1.txt"))
dimnames(sample1_data) <- list(list("a","b","c", "d"), list("I", "II", "III", "IV", "V"))
hist(sample1_data, probability = T, breaks = 5,main = "Histogram of Sample 1")
// (b)
x  = seq(0, 2, 0.001)
y1 = x^4 
y2 = 5*x + 2
plot(x, y1, col = "blue", type = "l",main = "Plot for y1(x) and y2(x)",xlab = "x",ylab = "y")
lines(x, y2, col="red",  type = "l", lty = 2)
legend(0, 15,legend=c("y1 = x^4", "y2 = 5*x + 2"),col=c("blue", "red"), lty=1:2, cex=0.8)
// (c)
load("Ass0.RData")
barplot(table(school), col = c("blue","green","black","yellow"),main = "Bar plot of \"school\" data")
// (d)
par(mfrow=c(1,1))
proportions <- c(0.37,0.17,0.28,0.07,0.06,0.05)
food_lables <- c("Pear", "Cheesecake", "Chocolate", "Almond", "Strawberry", "Other")
pie(proportions,labels = food_lables,main="Sales proportions of pie flavours")
```
